import { PageStack } from "@/styles";
import {
  Code,
  Flex,
  Heading,
  Link,
  List,
  ListItem,
  OrderedList,
  Text,
} from "@chakra-ui/react";
import { NextPage } from "next";
import Head from "next/head";
import NextLink from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Web3 Workshop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageStack spacing={8}>
        <Heading>From Blockchain To Browser</Heading>
        <Text fontSize="26px">Before we begin</Text>
        <Flex direction="column">
          <OrderedList alignItems="flex-start" textAlign="left">
            <ListItem>
              Get yourself some Sepolia Eth{" "}
              <Link
                target="_blank"
                href="https://www.alchemy.com/faucets/ethereum-sepolia"
              >
                HERE
              </Link>{" "}
              or{" "}
              <Link
                target="_blank"
                href="https://cloud.google.com/application/web3/faucet/ethereum/sepolia"
              >
                HERE
              </Link>
            </ListItem>
            <ListItem>
              Get a ThirdWeb API key{" "}
              <Link
                target="_blank"
                href="https://thirdweb.com/dashboard/settings/api-keys"
              >
                HERE
              </Link>{" "}
            </ListItem>
            <ListItem>Clone the workshop repo </ListItem>
            <Code>
              git clone git@github.com:simon-tanna/web3-workshop-monorepo.git
            </Code>
            <ListItem>Checkout the branch </ListItem>
            <Code>git checkout favourite-number-pg-scaffold</Code>
            <ListItem>
              Run <Code>yarn</Code>
            </ListItem>
            <ListItem>
              Then <Code>touch apps/workshop-client/.env</Code>
            </ListItem>
            <ListItem>
              Copy over the contents of .env.example to the .env file and add
              your ThirdWeb API keys.
            </ListItem>
          </OrderedList>
        </Flex>
      </PageStack>
    </>
  );
};

export default Home;
