import { PageStack } from "@/styles";
import { Container, Heading, Spinner, Text } from "@chakra-ui/react";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Web3 Workshop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageStack>
        <Heading>Hello World</Heading>
      </PageStack>
    </>
  );
}
